config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  scope "(:locale)", locale: /en|vi/ do
    namespace :api, {format: "json"} do
      namespace :v1 do
        namespace :admin do
          resources :books, only: %i(create update destroy)
          resources :categories, except: %i(new edit)
        end
        devise_scope :user do
          post "sign_in", to: "sessions#create"
          delete "sign_out", to: "sessions#destroy"
        end
        resources :users, only: %i(index show) do
          resources :following, only: :index
          resources :user_profiles, only: :update
        end
        resources :books, only: %i(index show) do
          resources :reviews, except: %i(new show edit)
        end
      end
    end
    root "home#index"
    devise_for :users, controllers: {sessions: "users/sessions", registrations: "registrations"},
      path: "", path_names: {edit: "change_password", sign_up: "register"}
    namespace :admin do
      root "home#index"
    end
    resources :books do
      resources :markers, only: %i(create destroy)
      resources :reviews
      get :autocomplete_book_title, on: :collection
      collection do
        resources :favorites, only: %i(index destroy)
        resources :readed_books, only: %i(index destroy)
        resources :reading_books, only: %i(index destroy)
        resources :book_filters, only: :index
      end
    end
    resources :users, only: %i(show) do
      resources :relationships, only: %i(create destroy)
      get :autocomplete_user_profile_name, on: :collection
      resources :following, only: :index
      resources :followers, only: :index
      resources :user_profiles, only: %i(update)
    end
    resources :purchase_requests, path: "purchase-requests",
      only: %i(index destroy)
    resources :user_book_searches, only: :index
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  authorize_resource class: Marker
  before_action :get_favorite, only: %i(destroy)

  def index
    @favorites = current_user.markers.created_at_desc
                             .where(status: :favorite).includes(:book)
  end

  def destroy
    if @marker.destroy
      flash[:success] = t ".success"
    else
      flash[:danger] = t ".destroy_failure"
    end
    redirect_to favorites_path
  end

  private

  def get_favorite
    return if @marker = current_user.markers.find_by(id: params[:id])
    flash[:danger] = t ".favorite_not_found"
    redirect_to favorites_path
  end
end

app/views/favorites/_favorite.html.erb
<tr>
  <td>
    <%= image_tag check_image_cover(favorite.book), class: "image-datatable" %>
  </td>
  <td><%= link_to favorite.book.title, book_path(favorite.book) %></td>
  <td><%= favorite.book.number_pages %></td>
  <td><%= favorite.book.author %></td>
  <td><%= favorite.book.price %></td>
  <td><%= l favorite.created_at, format: :datetime %></td>
  <td>
    <%= link_to t(".cancel"), favorite_path(favorite), method: :delete,
      data: {confirm: t(".confirm")} %>
  </td>
</tr>

app/views/favorites/index.html.erb
<% provide :title, t(".list_favorites") %>
<% provide :icon, "icon/books.png"%>
<div class="site-section" id="main-content">
  <div class="container">
    <div class="row mb-5">
      <div class="col-md-7 text-left border-primary">
        <h2 class="font-weight-light text-primary">
          <%= t ".list_favorites" %>
        </h2>
      </div>
    </div>
    <div class="col-md-12 mt-5" id="list-favorites">
      <table id="table-favorites"
        class="table table-striped table-bordered">
        <thead>
          <tr>
            <th><%= t ".cover_image" %></th>
            <th><%= t ".title" %></th>
            <th><%= t ".number_pages" %></th>
            <th><%= t ".author" %></th>
            <th><%= t ".price" %></th>
            <th><%= t ".favorite_time_at" %></th>
            <th><%= t ".action" %></th>
          </tr>
        </thead>
        <tbody>
          <%= render partial: "favorites/favorite", collection: @favorites %>
        </tbody>
      </table>
    </div>
  </div>
</div>