config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  scope "(:locale)", locale: /en|vi/ do
    namespace :api, {format: "json"} do
      namespace :v1 do
        namespace :admin do
          resources :books, only: %i(create update destroy)
          resources :categories, except: %i(new edit)
        end
        devise_scope :user do
          post "sign_in", to: "sessions#create"
          delete "sign_out", to: "sessions#destroy"
        end
        resources :users, only: %i(index show) do
          resources :following, only: :index
          resources :user_profiles, only: :update
        end
        resources :books, only: %i(index show) do
          resources :reviews, except: %i(new show edit)
        end
      end
    end
    root "home#index"
    devise_for :users, controllers: {sessions: "users/sessions", registrations: "registrations"},
      path: "", path_names: {edit: "change_password", sign_up: "register"}
    namespace :admin do
      root "home#index"
    end
    resources :books do
      resources :markers, only: %i(create destroy)
      resources :reviews
      get :autocomplete_book_title, on: :collection
      collection do
        resources :favorites, only: %i(index destroy)
        resources :readed_books, only: %i(index destroy)
        resources :reading_books, only: %i(index destroy)
        resources :book_filters, only: :index
      end
    end
    resources :users, only: %i(show) do
      resources :relationships, only: %i(create destroy)
      get :autocomplete_user_profile_name, on: :collection
      resources :following, only: :index
      resources :followers, only: :index
      resources :user_profiles, only: %i(update)
    end
    resources :purchase_requests, path: "purchase-requests",
      only: %i(index destroy)
    resources :user_book_searches, only: :index
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  before_action :admin?

  def index; end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    return unless current_user
    activities = Activity.where_user(current_user.following)
                         .includes user: :user_profile
    marker_activites = activities.markers.includes activitable: :book
    relationship_activites = activities.relationships.includes(
      activitable: {followed: :user_profile}
    )
    activities = (marker_activites + relationship_activites)
                 .sort_by(&:created_at).reverse
    activities = ActivityDecorator.decorate_collection activities
    @activities = Kaminari.paginate_array(activities)
                          .page(params[:page]).per Settings.activites
  end
end

app/views/home/_activity.html.erb
<div class="col-md-12 m-4 bg-white p-3">
  <div class="media">

    <%= image_tag activity.avt_user, class: "avatar-activity mr-3" %>

    <div class="media-body">

      <h5 class="m-0">
        <%= link_to user_path(activity.user) do %>
          <%= activity.user_name %>
        <% end %>

        <% if activity.marker? %>
          <%= t ".mark" %>
          <%= activity.status_maker %>
          <%= link_to book_path(activity.book_marker) do %>
            <%= activity.book_title_marker %>
          <% end %>
        <% end %>

        <% if activity.relationship? %>
          <%= t ".following" %>
          <%= link_to user_path(activity.followed_relationship) do %>
            <%= activity.followed_name_ralationship %>
          <% end %>
        <% end %>
      </h5>

      <%= activity.created_at %>

      <div class="media mt-2">
        <div class="media-body">

          <div class="mt-0 mb-2">
            <i class="fab fa-gratipay fa-lg c-gray like"
              title="<%= t ".like" %>"></i>
            <i class="fas fa-comment-dots fa-lg c-gray ml-3 comment"></i>
          </div>

          <div class="media mt-2">

            <%= image_tag check_avatar(current_user.user_profile),
              class: "mr-2 avt-repcmt" %>

            <div class="media-body">
              <%= form_with url: "#" do |f| %>
                <%= f.text_field :content, placeholder: t(".write_a_comment"),
                  class: "form-control write_comment" %>
              <% end %>
            </div>

          </div>

        </div>
      </div>

    </div>
  </div>
</div>

app/views/home/index.html.erb
<% provide :title, t(".home_page") %>
<% provide :icon, "icon/books.png"%>
<% if user_signed_in? %>
  <div class="site-section bg-light" id="main-content">
    <div class="container">
      <div class="row" id="activities-home-page">
        <%= render partial: "home/activity", collection: @activities %>
      </div>
      <div class="row justify-content-center" id="kaminari-activities">
        <%= paginate @activities, remote: true %>
      </div>
    </div>
  </div>
<% else %>
  <%= render "layouts/statistical" %>
<% end %>

app/views/home/index.js.erb
$("#activities-home-page").html(`
  <%= j render partial: "home/activity", collection: @activities %>
`);
$("#kaminari-activities").html("<%= j paginate @activities, remote: true %>");